### ISSUE TITLE
Messed up version?

### ISSUE THREAD

**Issue by oshimayoan** [kodefox/kfstart#3]
I'm pretty sure latest version should be above `0.18.0` but the latest version on NPM is `0.14.6`.

![image](https://user-images.githubusercontent.com/4923122/56127740-0ab09580-5fa8-11e9-9a5e-1937d5589aba.png)

cc @sstur

**Comment by sstur** [comment]
OK, I just bumped the version to 0.19.0 and ran `npm publish`
